### PR TITLE
it will scrape every competition on hackerearth

### PR DESCRIPTION
**Pull request by pyanishjain**
it is for other purpose but it might help with mlcontest

### CODE REVIEW

**Comment by hcarlens** [comment]
Thanks. I'd love to include this, but currently we have a static back-end since I'm hosting this for free on Github Pages. I see a few options for doing this:
1. We switch to a paid hosting provider that supports a Python back-end.
2. We run this script somewhere else as a cron job, and have it use the [GitHub API](https://developer.github.com/v3/) to make pull requests on this repo for competitions which aren't listed yet. 
3. We run this script somewhere else as a cron job, and have it email us when it finds a new contest. We can then manually add it to the site. 

Unfortunately #1 isn't really an option right now, as this site isn't making any money. I think #2 would be ideal at this point, but #3 would work too. What do you think? If you're interested in trying #2, you could try using [PyGitHub](https://github.com/PyGithub/PyGithub).

**Comment by pyanishjain** [comment]
What i have done is just scrape it and automatically make a json file and when i commit it will automatically update my website coderkabri.ml

**Comment by pyanishjain** [comment]
Only one day in a week i think we have to run script and it take 2- 3 min to everything 
But brother you should make your content in json and in seperate file and then use fetch api if you like i can do so

**Comment by pyanishjain** [comment]
Hey can we add all kind of competition what i said is visit coderkabri.ml
as you website is good and i think it's more impact full if it merge with mlcontest

**Comment by hcarlens** [comment]
Great - currently the data here is in json format too, but it's within the index.html file as that seems to significantly improve page load times. 

You're welcome to submit additions/changes to the json there: https://github.com/mlcontests/mlcontests.github.io/blob/master/index.html#L53

**Comment by pyanishjain** [comment]
brother you are paying for .com from where you buy it

**Comment by merrcury** [comment]
Why don't you give a try to heroku? It's free plan will do job for small websites,

**Pull request closed without merging**
