### PR TITLE
Global Economic Forecast Hackathon

### PR DESCRIPTION
**Pull request by nicolasoblivious**
We are hosting another (https://github.com/mlcontests/mlcontests.github.io/pull/234) privacy machine learning competition!

### CODE REVIEW

**Comment by hcarlens** [comment]
Thanks @nicolasoblivious, and sorry for the delay!

**Comment by nicolasoblivious** [comment]
Hey @hcarlens! Thank you, and no worries at all! 

I just wanted to check in since it appears to be that the competition is not showing up on the website, is there anything else that I should be doing on my end that I may be missing? 

Thanks again!

**Comment by hcarlens** [comment]
Fixed sorry, site cache was stale! Let me know if you see any other issues.

**Comment by hcarlens** [comment]
Hi @nicolasoblivious, I'd like to get a bit more info about Antigranular for our upcoming report. Could you send me an email at `harald@<my site url>` please?

**Pull request merged**
