### PR TITLE
add two new challenges fix urls for currently live challenges

### PR DESCRIPTION
**Pull request by DmytroObertan**

### CODE REVIEW

**Comment by DmytroObertan** [comment]
@hcarlens Hi. Could you please take a look into this? Challenges are live.

**Comment by hcarlens** [comment]
Will do. At NeurIPS this week, I’ll try to take a look at the weekend. Is
your platform being renamed?

**Comment by DmytroObertan** [comment]
@hcarlens Yeah. We are thinkonward.com now :)

**Comment by hcarlens** [comment]
Thanks. Could you ask someone from the business/product side to get in touch with me by email? I've been trying to reach Nate the past few weeks but haven't received a response.

**Pull request merged**
