### PR TITLE
adding json and index.js file

### PR DESCRIPTION
**Pull request by pyanishjain**
hey jsut see i added json and index.js file to make code more readable

### CODE REVIEW

**Comment by hcarlens** [comment]
When I try to run these changes, the content doesn't load:
```
Fetch API cannot load ***/mlcontests.github.io/data.json. URL scheme must be "http" or "https" for CORS request.
index.js:20 Uncaught (in promise) TypeError: Failed to fetch
    at index.js:20
(anonymous)	@	index.js:20
```

**Comment by pyanishjain** [comment]
fetch api alway needed http and https server so please use local server to see chages 
if you are using vs code install live server and open website with it you see the results

**Comment by pyanishjain** [comment]
as their is no problem if you updated in github as from their github servers it

**Comment by hcarlens** [comment]
Thanks. How does the page load time compare vs the master branch?

**Comment by pyanishjain** [comment]
i see no chage in page time laoding 
as their is only one json file to laod 
if you see any time delay let me know
as my coderkabri.ml works fine with this .it have same amount of data

**Comment by pyanishjain** [comment]
hey hcarlens you did't merge my code with yours it did't work let me know cause it work fine for me

**Comment by hcarlens** [comment]
Hey - I want to do some performance testing on my side before merging this in. Will get around to it.

**Comment by pyanishjain** [comment]
is json file is not working

**Comment by hcarlens** [comment]
I did some extra performance testing locally and didn't see any difference in load times in the end (both around 400-500ms). I've deployed it now and there does seem to be a bit of a flickering effect when the page loads, which wasn't there before. It's not the end of the world though, worth it for having the data in a separate file. Thanks!

**Pull request merged**
