### PR TITLE
added new ITU GEOAI and 5G Challenges

### PR DESCRIPTION
**Pull request by gblessed**
added new ITU GEOAI and 5G Challenges.

### CODE REVIEW

**Comment by gblessed** [comment]
Hi @hcarlens 
We could link the following pages
1. ITU 5G Challenges: https://aiforgood.itu.int/about-ai-for-good/aiml-in-5g-challenge/
(under this challenge, we have several problem statements that participants can choose from).
Prize per problem statement: The winner of each problem statement will receive a cash prize of 1’000 CHF.
·       Prize across all problem statements

o   Overall Best Solution [ITU AI/ML in 5G Challenge Gold Champion] 3’000 CHF

o   Overall Best runner up solution [ITU AI/ML in 5G Challenge Silver Champion] 2’000 CHF

The Judges Panel may decide to split prizes.
·       Audience prize, based on a customized poll run by ITU during the Grand Challenge Finale: 300 CHF.
·       Student award: 500 CHF.

GeoAI: https://aiforgood.itu.int/about-ai-for-good/geoai-challenge/

7.3 Prizes  (described prizes: https://2ja3zj1n4vsz2sq9zh82y3wi-wpengine.netdna-ssl.com/wp-content/uploads/2020/12/ITU_GeoAI_Challenge_Participation_guidelines_2022_final.pdf)

I hope its clear?

**Comment by gblessed** [comment]
Here are the list of problem statements for the GeoAI challenge (3) -> https://geoaichallenge.aiforgood.itu.int/match
Here are the list of problem statements for the AI/5G challenge  (2022 problem statements)-> https://challenge.aiforgood.itu.int/match.

Is this ok?

**Comment by gblessed** [comment]
Hi @hcarlens  anything else? or are we good to go?

**Comment by hcarlens** [comment]
Thanks @gblessed. I'm travelling this week so a bit slow to respond. I haven't fully decided yet what the best way to represent the sub-competitions is, but I've merged your PR in for now with minor changes (date formatting and prizes as rough USD values)

**Comment by hcarlens** [comment]
Hi @gblessed, I have a few more questions about these competitions - do you have an email address I could reach you on?

**Comment by gblessed** [comment]
***@***.***

**Comment by hcarlens** [comment]
This doesn't show up for me - could you email me at info@mlcontests.com? I'd like to collect some extra data about these competitions for a report.

**Pull request merged**
