### PR TITLE
added DC scholarship competition

### PR DESCRIPTION
**Pull request by maartenvandenbroeck**
Hi Harald! @hcarlens 

Excited to be able to share our first DC competition. It's a bigger one, aimed towards beginners and anyone who wants to learn data. Thanks!

### CODE REVIEW

**Comment by hcarlens** [comment]
Hey Maarten! This looks like a great competition. 

I'd love to send people here but still have the same reservations as the last time we spoke - the competition description and rules (https://app.datacamp.com/learn/competitions/python-scholarship-2023?activeTab=competition-overview) aren't visible without being logged in. I think including this in the competitions list would lead to a frustrating user experience. The norm is for anyone to be able to read competition rules and details, and then create a login for a particular platform if they want to participate.

**Comment by maartenvandenbroeck** [comment]
Thanks! We created this logged-off page (the one shared in the PR) for that, but do you also want the judging criteria to be visible here? Or what other details would you like to see?

**Comment by hcarlens** [comment]
A few things:
- The definition of Challenge 2 seems different on the logged-in page and the logged-off page
- It would be nice if it was clearer on the logged-off page that this is a subjectively judged challenge, rather than a metric-driven one (I didn't really notice that until I all the way down at "selecting the recipients"). Something more explicit near the top of the page saying something like "build the best data exploration notebook" would be better. E.g. look at these Kaggle competitions for inspiration [1](https://www.kaggle.com/competitions/nfl-big-data-bowl-2024) [2](https://www.kaggle.com/competitions/2023-kaggle-ai-report)
- Listing the full judging criteria on the logged-off page would be ideal, or at least a very basic description of the judging criteria. E.g. "Your work will be judged based on a mix of public upvotes, response quality, storytelling, and presentation quality.". 
- From the logged-in page it looks like it's probably necessary to use Python+SQL in this challenge - "Start your analysis in Python and SQL" - whereas this isn't totally clear on the logged-off page. 
- A little more information about each of the challenges would be good. E.g. the number of rows in each of the datasets, and the 6 questions per challenge that are listed when you open a workspace. That would make it clearer that it's entry-level from a data science point of view and that the focus will be on communication/presentation.

Separately, on the prize money - "$5,000 for the winner to use towards further learning or formal education" - will that be given to the winners in cash, or do they have to decide up-front on what to spend it on?

**Comment by maartenvandenbroeck** [comment]
Thanks Harald!


Great points. I've implemented the feedback.

Regarding the prize money: it will be cash, so they can later decide what to spend it on, however, it should be spend on education in some form.

- [x] The definition of Challenge 2 seems different on the logged-in page and the logged-off page

Good catch! (you might need to clear your cache to see the change)
- [x]  It would be nice if it was clearer on the logged-off page that this is a subjectively judged challenge, rather than a metric-driven one (I didn't really notice that until I all the way down at "selecting the recipients"). Something more explicit near the top of the page saying something like "build the best data exploration notebook" would be better. E.g. look at these Kaggle competitions for inspiration [1](https://www.kaggle.com/competitions/nfl-big-data-bowl-2024) [2](https://www.kaggle.com/competitions/2023-kaggle-ai-report)

Agreed. I added another paragraph on top of the page. also "subjectively" was one of the tags, are these visible on the webpage of MLContests?
- [x] Listing the full judging criteria on the logged-off page would be ideal, or at least a very basic description of the judging criteria. E.g. "Your work will be judged based on a mix of public upvotes, response quality, storytelling, and presentation quality.".

Done.
- [x] From the logged-in page it looks like it's probably necessary to use Python+SQL in this challenge - "Start your analysis in Python and SQL" - whereas this isn't totally clear on the logged-off page.

This was from some legacy instructions, fixed now!
- [x] A little more information about each of the challenges would be good. E.g. the number of rows in each of the datasets, and the 6 questions per challenge that are listed when you open a workspace. That would make it clearer that it's entry-level from a data science point of view and that the focus will be on communication/presentation.

Valid point. I added some more details about the challenges, to make it clear it is beginner-like. I left out the number of rows, as that is part of the questions ;)

**Comment by hcarlens** [comment]
Great changes, merged to production. I've made some small changes to how it shows up in the list. The tags aren't shown on the front-end yet, that's a change I still need to make sometime!

**Comment by maartenvandenbroeck** [comment]
Hi @hcarlens! Thanks for publishing it. Can we have a more catchy title? :) Something that includes dinosaurs/movies?

**Comment by hcarlens** [comment]
Sure, done.

**Pull request merged**
