### PR TITLE
add three new thinkonward challenges

### PR DESCRIPTION
**Pull request by DmytroObertan**

### CODE REVIEW

**Comment by hcarlens** [comment]
Thanks - I'll trim down the challenge names a bit and merge in next week once they've launched!

**Comment by DmytroObertan** [comment]
@hcarlens Could you please merge this PR? Challenges are live on https://thinkonward.com/app/c/challenges.
Thanks a lot!

**Comment by DmytroObertan** [comment]
@hcarlens Hi. We cannot see the challenges in the https://mlcontests.com/
Is that expected? Maybe we need to do some extra steps?

**Comment by hcarlens** [comment]
Apologies @DmytroObertan, it looks like they were accidentally removed in a mishandled merge conflict. 
I've fixed this, and they're visible again now. There are no extra steps required, and this shouldn't happen again.

**Pull request merged**
