### PR TITLE
Adding Weather4cast 2022 NeurIPS competition

### PR DESCRIPTION
**Pull request by agruca-polsl**

### CODE REVIEW

**Comment by hcarlens** [comment]
Hi @agruca-polsl! Thanks for contributing. I think the Weather4Cast competition is already represented on the website, but maybe some of the data is wrong/missing. Would you prefer for the URL to be weather4cast.ai rather than https://www.iarai.ac.at/weather4cast/ ?

**Comment by agruca-polsl** [comment]
Hi @hcarlens!

Weather4cast competition has been already added to the mlcontests website previously but this a general name of the weather prediction competitions organised by IARAI and in 2022 we organise a new challenge under this name which is a part of the NeurIPS competition track.

Regarding the URL - both of them work and point to the same website.

**Comment by agruca-polsl** [comment]
Hi @hcarlens,

Ah, I have looked trough the  list of the competitions and actually you are right, it is already represented. It seems that one of my colleagues must have added it. I would like to add the some more details such as prizes. How the best do it? Shall I edit the previous entry?

**Comment by hcarlens** [comment]
That's great - I went through and added some of this year's NeurIPS competitions a while ago, so maybe I added it! 

I've incorporated your changes, though I kept the competition description short since that works better on the page. I also represented the prize in USD like all the others so it makes sense for the sort. If you're happy with this representation then I'll merge it in.

**Comment by agruca-polsl** [comment]
Thank you very much! 

I am perfectly fine with both keeping competition description short and representing prizes in USD. Please merge in the changes.

**Comment by hcarlens** [comment]
Thanks, that's live on the site now! 

We'll be highlighting some of the winning techniques for competitions later this year, so if it's ok with you I'll get in touch with you once the competition is over. 

I've sent you an invite to connect on LinkedIn.

**Comment by hcarlens** [comment]
@agruca-polsl FYI I've sent you a message on LinkedIn about some info on the winners.

**Pull request merged**
