### PR TITLE
Proposal: move competitions data to external file and automatically filter finished tasks.

### PR DESCRIPTION
**Pull request by Tenich**
Hi! 

This pull proposes to move list of competitions to `data.js` file, to increase readability and adds filtering out competitions with negative `days_until_deadline`. 

I propose to store all competitions data (even past) and later add filter to be able to search over all competitions (it's useful when you are looking for similar competitions to gather solution insights or datasets)

It's also makes life easier, as you don't have to remove past competitions by hand.

### CODE REVIEW

**Comment by hcarlens** [comment]
Hey @Tenich, thanks for this! On your point about filtering, I think that should be happening already: https://github.com/mlcontests/mlcontests.github.io/blob/master/index.html#L290  - please let me know if that's not what you're seeing in your browser. 

I would much prefer to have the data in a separate file, but when I tested that initially it made the page load noticeably slower. If we can find a way to do it that doesn't impact performance I'd be all for it!

**Comment by pyanishjain** [comment]
hey i made a script that automatically fetch data from kaggle competions save in database so let me know about it @helloanishjain@gmail.com

**Comment by pyanishjain** [comment]
hey Anton Pankratov i just added that when file scrape from hackerearth it will made a json file of all 
competition and links

**Comment by pyanishjain** [comment]
> Hey @Tenich, thanks for this! On your point about filtering, I think that should be happening already: https://github.com/mlcontests/mlcontests.github.io/blob/master/index.html#L290 - please let me know if that's not what you're seeing in your browser.
> 
> I would much prefer to have the data in a separate file, but when I tested that initially it made the page load noticeably slower. If we can find a way to do it that doesn't impact performance I'd be all for it!
use json file

**Comment by hcarlens** [comment]
> > Hey @Tenich, thanks for this! On your point about filtering, I think that should be happening already: https://github.com/mlcontests/mlcontests.github.io/blob/master/index.html#L290 - please let me know if that's not what you're seeing in your browser.
> > I would much prefer to have the data in a separate file, but when I tested that initially it made the page load noticeably slower. If we can find a way to do it that doesn't impact performance I'd be all for it!
> use json file
I'd consider it if you could show that the performance is comparable when using a separate json file, but when I tried this myself it was noticeably slower.

**Comment by hcarlens** [comment]
Closing this since filtering was implemented in https://github.com/mlcontests/mlcontests.github.io/commit/98b536fe26336c96a12336e94a8cbf2eb315e486 and I decided to go with the separate data file method from https://github.com/mlcontests/mlcontests.github.io/pull/22 using fetch, since that will make it easier to move to alternative sources (e.g. a db) if we choose to. 
Thanks for the suggestions!

**Pull request closed without merging**
