### PR TITLE
Add Exun 2021-2022

### PR DESCRIPTION
**Pull request by Bhuvneshn**

### CODE REVIEW

**Comment by hcarlens** [comment]
Hi @Bhuvneshn! Thanks for contributing. Am I right in thinking that this is a series of competitions, including sudocrypt as one of them? If so, would it make sense to list each of the competitions separately? Do they all have the same deadline?

**Comment by Bhuvneshn** [comment]
Hi, @hcarlens! Yes, Sudocrypt is one of our flagship events. We are trying to list this event, particularly on mlcontests.com as it is our ML event. 
All the events have different deadlines. The one I have mentioned is of our ML Prelims.

**Comment by hcarlens** [comment]
Thanks. How many of your competitions are ML-related? Would it be possible for you to just list those, along with their deadlines? 
Just linking to exunclan.com is a bit confusing because it's not easy to find the list of events from there.

**Comment by Bhuvneshn** [comment]
This is our only ML event.  This is the link to our events page - https://reg.exun.co/invite/events. It has all our events listed and you can search ExML in the search bar to view the details for our ML event.

**Comment by hcarlens** [comment]
Thanks - in that case I'd prefer to link directly to the ExML event: https://reg.exun.co/invite/events/10
What is the prize money available just for the ExML event?

**Comment by Bhuvneshn** [comment]
We have prizes worth $2000 for the ML event. I'll make the changes and make a new pull request.

**Comment by hcarlens** [comment]
No need to create a new one, I've edited your PR
Just one last thing - will the competition actually run on Kaggle? If not I'd prefer to have something like "Exun" as the platform name. 
I'm about to head out for a while but will review and accept when I'm back

**Comment by Bhuvneshn** [comment]
Yes, the event will be hosted on Kaggle.

**Pull request merged**
